---
- name: lvm
  hosts: rhel8
  tasks:
          #  - name: create partion
          #    parted:
          #      device: /dev/sdb
          #      number: 1
          #      state: present
          #      part_end: 900M
          #      part_type: primary

  - name: create vg
    lvg:
      vg: research
      pvs: /dev/sdb1
    when: ansible_devices.sdb.partitions.sdb1 is defined and ( 'rhel8' in inventory_hostname )
  - name: create lv
    lvol:
      vg: research
      lv: data
      size: 1200M 
    #when: ansible_lvm.vgs.research is defined and (( ansible_lvm.vgs.research.size_g | float) > 1.2)  
    when: ('research' in ansible_lvm['vgs'] ) and (( ansible_lvm.vgs.research.size_g | float  ) > 1.2)  
  - name: send error 
    debug:
      msg: Could not create logical volume of that size
    when: ansible_lvm.vgs.research is defined and (( ansible_lvm.vgs.research.size_g | float) < 1)  
  - name: create lv
    lvol:
      vg: research
      lv: data
      size: 800M 
      #when: ansible_lvm.vgs.research is defined and (( ansible_lvm.vgs.research.size_g | float) < 1.2)  
    when: ('research' in ansible_lvm['vgs'] ) and (( ansible_lvm.vgs.research.size_g | float  ) < 1.2)  
  - name: create fs
    filesystem:
      fstype: ext4
      dev: /dev/research/data
  - name: mount
    mount:
      path: /data
      src: /dev/research/data
      fstype: ext4
      state: present
    when: ('qa' in group_names)
